general:
  set verbose: true
stage:
  gctsDeploy:
        host: 'phlhdr07.phl.sap.corp:8001',
        client: '200',
        abapCredentialsId: 'ABAPUserPasswordCredentialsId',
        repository: 'fordtest2','
