general:
  set verbose: true
stage:
  gctsDeploy:
        host: 'phlhdr07.phl.sap.corp:8001',
        client: '200',
        username: 'I058626',
        password: 'Rsbdcos0',
        abapCredentialsId: 'ABAPUserPasswordCredentialsId',
        repository: 'fordtest2','
