stage:
  gctsDeploy:
        client: '200',
        host: 'http://phlhdr07.phl.sap.corp:8011',
        password: 'Rsbdcos0',
        repository: 'fordtest3',
        username: 'I058626'
        
        
